language: node_js
node_js:
  - "node"
install:
  - npm install
script:
  - npm run test
after_success:
  - surge --project ./build --domain taskflow.surge.sh

deploy:
  provider: surge
  project: ./build/
  domain: taskflow.surge.sh  

